# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os: linux
dist: bionic

warnings_are_errors: false

git:
  depth: 1

jobs:
  include:
  - r:
      - release
    env:
      global:
        - R_BUILD_ARGS="--no-build-vignettes --no-manual"
        - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
        - _R_CHECK_TIMINGS_="0"
        - MECAB_LANG="ja" ## Japanese
    before_install:
      - sudo apt install mecab
      - sudo apt install libmecab-dev
      - sudo apt install mecab-ipadic-utf8
  - r:
      - release
    env:
      global:
        - R_BUILD_ARGS="--no-build-vignettes --no-manual"
        - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
        - _R_CHECK_TIMINGS_="0"
        ## - MECAB_LANG="" ## Korean
    before_install:
      - wget "https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz" -O mecab-0.996-ko-0.9.2.tar.gz
      - tar zxfv mecab-0.996-ko-0.9.2.tar.gz
      - ./configure
      - make
      - make check
      - sudo make install
      - wget "https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz" -O mecab-ko-dic-2.1.1-20180720.tar.gz
      - tar zxfv mecab-ko-dic-2.1.1-20180720.tar.gz
      - cd mecab-ko-dic-2.1.1-20180720
      - ./configure
      - make
      - sudo make install
      - cd ../

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

cache: packages
